name: velbus-tcp
version: 1.4.0
base: core18
summary: Python application that bridges a Velbus installation with TCP
description: |
  Python application that bridges a Velbus installation with TCP.

grade: stable
confinement: strict

apps:
  velbus-tcp:
    command: python3 $SNAP/__main__.py --settings $SNAP_DATA/settings.json
    daemon: simple
    plugs: [network-bind, serial-port, raw-usb]

parts:
  src:
    plugin: dump
    source: https://github.com/velbus/python-velbustcp.git
    source-tag: 1.4.0
    stage-packages: [openssl]

  extra: 
    plugin: dump
    source: extra

  python:
    plugin: python
    python-version: python3
    python-packages: [pyserial, pytz, tzlocal]
