name: velbus-tcp
version: 1.7.0
base: core22
summary: Python application that bridges a Velbus installation with TCP
description: |
  Python application that bridges a Velbus installation with TCP.

grade: stable
confinement: strict

apps:
  velbus-tcp:
    command: bin/python3 -m velbustcp --settings $SNAP_DATA/settings.json
    daemon: simple
    plugs: [network-bind, serial-port, raw-usb]

parts:
  extra: 
    plugin: dump
    source: extra

  src:
    plugin: python
    source: https://github.com/velbus/python-velbustcp.git
    source-branch: releases/1.7.0
    python-packages: [pyserial, pytz, tzlocal]
    stage-packages: [openssl]
